name: Build Desktop Apps

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-latest is for arm64 build, macos-13 is for x86_64
        os: ["windows-latest", "macos-latest", "macos-13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"

      - run: pip install -r requirements.txt

      # Compress MacOS app param ignored on Windows
      - run: sh ./desktop/build_desktop_app.sh --compress-mac-app
      - uses: actions/upload-artifact@v4
        with:
          name: kiln-desktop-${{ runner.os }}-${{ runner.arch }}
          path: ./desktop/build/dist/*
