name: Build Desktop Apps

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "macos-latest", "macos-13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"

      - run: pip install -r requirements.txt

      - run: sh ./desktop/build_desktop_app.sh
      - uses: actions/upload-artifact@v4
        with:
          name: fune-desktop-${{ matrix.os }}
          path: ./desktop/build/dist/*
