name: Build and Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Install Core
        run: poetry install
        working-directory: ./libs/core

      - name: Build Core
        run: poetry build
        working-directory: ./libs/core

      - name: Test Core
        run: python3 -m pytest tests/
        working-directory: ./libs/core

      # Remove this later: needed as server expects this dir to exist
      - name: Mock Studio Web UI
        run: mkdir -p ./src/web_ui/build

      - name: Test Studio
        run: python3 -m pytest tests/
        working-directory: ./libs/studio

      - name: Build Studio
        run: poetry build
        working-directory: ./libs/studio

      - name: Check Types Core
        run: mypy --install-types --non-interactive .
        working-directory: ./libs/core

      - name: Check Types Studio
        run: mypy --install-types --non-interactive .
        working-directory: ./libs/studio
