name: Build Desktop Apps

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-latest is for arm64 build, macos-13 is for x86_64
        os: ["windows-latest", "macos-latest", "macos-13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: "pip"

      - run: pip install -r requirements.txt

      - run: sh ./desktop/build_desktop_app.sh
      # MacOS apps have symlinks, and the artifact upload zip will break them. Tar instead.
      - run: cd build/dist && tar czpvf fune.app.tgz fune.app && rm -r fune.app && echo "Ready to upload"
      - uses: actions/upload-artifact@v4
        with:
          name: fune-desktop-${{ runner.os }}-${{ runner.arch }}
          path: ./desktop/build/dist/*
