name: Build Desktop Apps

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # macos-latest is for arm64 build, macos-13 is for x86_64
        os: ["windows-latest", "macos-latest", "macos-13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      # Compress MacOS app param ignored on Windows
      - run: uv run sh ./app/desktop/build_desktop_app.sh --compress-mac-app
      - uses: actions/upload-artifact@v4
        with:
          name: kiln-desktop-${{ runner.os }}-${{ runner.arch }}
          path: ./app/desktop/build/dist/*
